spring.application.name=table-booking
server.port=3000

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/seats_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (Hibernate) Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
